### ISSUE TITLE
code errors in md conversion to docx

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#1]
Whenever a backslash or underscore occurs in an .md, it must be preceded by an escape character (unless it is in a code block) or pandoc will delete the following word when rendering into docx. (Various errors throughout instruction files.)
(*edit to reduce this to a single issue)

**Comment by JasonHershey** [comment]
Thanks @itbland. I merged in the fixes you made and will be doing two things to fix this problem.  One will be making updates to the automation that creates markdown files from the source (this content is not natively authored in markdown).  And, for this course in particular, I'll be going through and reviewing formatting issues that you and others have noticed, and make updates for the escape character issues as I go.

**Comment by itbland** [comment]
Why use markdown at all? If the labs are docx to start, and we just convert them back using an inferior conversion program, why not just post the docx? The pull request option was hardly used in the Azure lab docs, most people jut open issues.
By the way, the paragraph formatting is horrid! I've messed with the template doc a lot and can't get the indents to function correctly, no matter what I do.
