### ISSUE TITLE
Mod 02 Lab B, Task 5, Step 2

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#10]
> Set-MsolPasswordPolicy -DomainName "Adatumyyxxxxx.onmicrosoft.com" -ValidityPeriod "90" -NotificationDays "14"

This sets the password policy back to normal for only the **Adatumyyxxxxx.onmicrosoft.com** domain, but leaves the **yourdomain.hostdomain.com** (the domain used throughout the rest of the course) set to 14/14. Was this the intent? Should we either change this instruction to the **_yourdomain.hostdomain.com_**  domain or add a command to **_ALSO_** change the **_yourdomain.hostdomain.com_** domain? (Which would add the information that each domain **_can_** have its own password policy if you use PowerShell instead of the GUI.)

**Comment by JasonHershey** [comment]
Not sure of exact original intent, but I think you are correct that for consistency with the rest of the course and with reality (I don't know anyone who messes with the onmicrosoft.com domain once they have their custom domain(s) set up.)   Your comment about being able to set policy by domain is a good one to bring up when teaching, though.

**Comment by JasonHershey** [comment]
change made in lab and LAK
