### ISSUE TITLE
Mod 04 Exercise 2, Task 2

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#11]
Azure AD connect was updated in May 2017, When adding a local directory you now must choose to use a service account or specify an Enterprise admin and have AD Connect create a service account for the connector. This lab step (and the LAK) should be updated to something like: 

> On the **Connect your directories** page, click **Add Directory**, select **Create new account**, enter the credentials **ADATUM\Administrator**, and the password **Pa55w.rd**, click **OK**, verify that **Adatum.com** is now listed under **CONFIGURED DIRECTORIES**, and then click **Next**.

**Comment by JasonHershey** [comment]
Updated.
