### ISSUE TITLE
Mod 02, Lab B, Exercise 3, Task 1 

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#12]
When designating admins, O365 no longer requires an email address, but if we add one, you now need to click the EDIT button above the email address text box before you can type the address.

**Comment by JasonHershey** [comment]
Update the exercise to remove all but one instance of adding the alternate address, since it was the same for each. I left in one and changed the instructions, to illustrate how its done.

**Comment by itbland** [comment]
I **like** that solution! Do it _AND_ save time!
