### ISSUE TITLE
Mod 05 Lab & LAK, Exercise 1, Task 2, Step 3

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#13]
This instruction is easily misunderstood. I suggest we add "below the **\<Configuration\>** tag" or some other clarification that we do not remove the comments on the paragraph above the configuration, nor should we remove the entire lines with the comment codes (been there, done that!).

Proposed change:
3. In Notepad, remove all the remaining comment codes ( "**\<!--**" and "**--\>**" ) below the **\<Configuration\>** tag.

**Comment by itbland** [comment]
Clarification: 
In the Lab document Ex 1, Task 2 

> 3. Remove all comments from the code.

Should be something like: 

> 3. Remove all comment codes in the \<Configuration\> section. 

or

> 3. Remove all comment codes below this point.

In the LAK, Ex 1, Task 2, the instruction is a real problem

> 3. In Notepad, remove all the remaining comment codes (lines that start with \).

It should **_not_** say **_lines that start with_**! The only way to interpret that is to delete those three lines entirely. We are doing an unattended install, the Display and EULA line needs to be in the xml. 
How about something like:

> 3. In Notepad, remove the comment codes (\) from the three lines at the bottom of the file.

**Comment by JasonHershey** [comment]
Updated these instructions based on other feedback about this section.  I think its more clear now.
