### ISSUE TITLE
Mod 05, Ex 2, Task 1, Step 26

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#14]
> Note: This user has a license, but Skype for Business 2016 and Office 2016 are not available for download because Holly disabled Office download. _Skype for Business 2015 is available since it has not been disabled._

Skype for Business 2015 no longer appears on the software page. This note should have that reference removed, and should look like:

> Note: This user has a license, but Office 2016 and Skype for Business 2016 are not available for download because Holly disabled Office 2016 downloads.

**Comment by JasonHershey** [comment]
Updated. will check in with other changes
