### ISSUE TITLE
Lab Answer Key: Module 8, Ex 1, Step 5 -- PowerShell now requires a restart

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#15]
Exercise 1, Step 5, should be updated to something like:  

5. After the installation completes, click **Restart**.
6. Sign in to LON-CL1 as **ADATUM\Holly** with the password **Pa55w.rd**
7. On the **Setup Complete** window, click **Close**

**Comment by JasonHershey** [comment]
verified the bug and updated the lab steps
