### ISSUE TITLE
Mod 04 Lab

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#16]
By the end of the mod 04 lab, we have not enabled the sync scheduler--is this intentional, or an oversight?

**Comment by JasonHershey** [comment]
The sync scheduler is automatically enabled during installation.  Just run Get-ADSyncScheduler to verify.

**Comment by itbland** [comment]
Sorry, my lab provider has their own set of instructions, and in theirs it is not enabled--**BUT**, enabling during the AD Connect wizard **_directly contradicts the teaching in the Module_**. We **_should_** uncheck the box at the end of the wizard and then, after all the filters are set, run Set-ADSyncScheduler
