### ISSUE TITLE
Mod 09 LAK, Ex 3, Task 2, Step 11 - Need to use a different "outside" email

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#17]
The instruction is:

> In the Share 'Accounts Project' dialog box, type in **_the email address of the Microsoft account you used to set up Office 365._**

Office 365 will recognize this as Holly. The instruction needs to be changed to use another outside email address that the student can access from the lab.

**Comment by JasonHershey** [comment]
I checked on this.  The email that you should use for this (and for the signup) should be an outside email address. In module ones students are told to use a Microsoft account or other email for the signup.  Instructor notes for the lab make the recommendation that the instructors tell students to create a new MSA just for the course.   Even though the name entered is "Holly" when signing up, because the email is external, o365 should not think its Holly

**Comment by itbland** [comment]
Did you try it? Starting 2-3 months ago, when typing in the Outlook.com account I used as the address to create the trial account, the TO: field populates with "Holly Dickson" and cannot be changed to just the email address. The email is sent to Holly@Adatumyyxxxxx.hostdomain.com, not the outlook.com address, so it is not demonstrating external sharing.

________________________________

**Comment by JasonHershey** [comment]
I just tried this on my own tenant and was able to do it.  I did get a very confusing experience during this.  When I started typing the address I used to set up my tenant, my in-tenant account in showed up in the people picker making it seem like I had to choose that option.  In fact, it was appearing over what I was typing, so I typed a semi-colon after the email address and it entered as expected.  I'm just wondering if you maybe had this same experience?

**Comment by itbland** [comment]
I wii give it another shot, I could not come up with the correct sequence to stop it from converting the address into Holly, in any event, we would need a note that the student not accept the conversion to Holly here, and when testing DLP in Mod 11
________________________________

**Comment by itbland** [comment]
I absolutely cannot get this to work. Possibly there is something in the logic of newly setup accounts that is different than older tenants. Please feel free to try in my tenant from last week's class--it was setup following all directions from the class, and all labs have been completed. The Lab custom domain is using federation, but Holly@ is just using the default password. The On Microsoft domain is AdatumLOD39062 and the email used to set up the tenant is etb20347a (Outlook address as suggested). When attempting to share a document per Mod 09, or send the DLP-triggering email in 11, it ALWAYS converts the typed Outlook address to "Holly Dickson" and sends the email to the internal O365 address, not the Outlook address.

**Comment by JasonHershey** [comment]
Thanks. I'll try out on your domain. That said, I don't see any reason that you can't instruct students to share out to a different email address. The goal of that exercise is to share externally, not share to 'holly' so if a different address will work, go for it.  You might need students to create a new outlook.com address just for that purpose if for some strange reason they don't have an email address that would work.

**Comment by itbland** [comment]
Yes, I tell them to use a REAL outside address they already have, I just don’t like the idea of mixing their real world with the lab.

--Eric
