### ISSUE TITLE
Lab Answer Key: Module 5: Planning and deploying Office 365 ProPlus Ex 1, Task 2

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#21]
The instruction: 

> 4. In Notepad, remove all the remaining comment codes (lines that start with ).

is incorrect, the comment tags should be deleted, leaving the three lines. 
In particular, the **Display Level="None"** needs to stay

**Comment by JasonHershey** [comment]
Yes, Display config does need set. The other two don't need set. The first is set to the default value (so if not set, its this value).  Autoactivate does not apply to ProPlus. I'm thinking best idea is to call out deleting those two lines and removing comments from the Display config line.  I'll make the update along with the other changes to this mod

**Comment by itbland** [comment]
I liked the original instructions where we set the update path back to the same file share, it reinforced the idea that you could control the updates yourself. 
I also had the students alter the logging instruction to write the log file back to the share--(that I did to make troubleshooting much easier for me.)
