### ISSUE TITLE
Mod 10 LAK, Ex2, Task 2

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#22]
> 6. See how the document icon in **_the taskbar_** changes from two blue arrows to a small green check mark icon

Should be changed to:
6, See how the document icon in **File Explorer** changes from two blue arrows to a small green check mark icon

**Comment by JasonHershey** [comment]
Updated instruction. Will check in with other chagnes.
