### ISSUE TITLE
Mod 05 LAK

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#23]
When working in the Office16 folder, it would eliminate a lot of student errors if with make file extensions visible.

**Comment by JasonHershey** [comment]
What kind of errors are we running into?  I think this should be something as an instructor you should feel free to suggest to students.  (I admit that I do this automatically whenever I get a new machine)

**Comment by itbland** [comment]
Saving the **AdatumConfiguration.xml**, it is VERY easy to save it as **.xml.txt** (even with the warning) and I even had one student save it as .xml.xml this past week and we couldn't see _THAT_ until we made them visible.
(In general I HATE that default setting, although I entirely understand it is needed for unsophisticated users on home computers.)

**Comment by JasonHershey** [comment]
Gotcha.  Not a perfect fix, but I will also add a note to the save step to emphasize the possible area.  And, I'll mention to the folks I know involved in lab setup instructions about adding this as a common config to machines
