### ISSUE TITLE
Mod 10 LAK, Exercise 3, Task 2

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#24]
> 1. On LON-CL1, **_double-click_** Windows Azure Active Directory Module for Windows PowerShell on the desktop.

PowerShell should **_ALWAYS_** be **Run as Admin**, when used with Office 365,
 http://powershell.office.com/get-started

**Comment by JasonHershey** [comment]
Corrected. checking in with some other fixes
