### ISSUE TITLE
Module 7: Planning and configuring Exchange Online services Lab A & B (& LAK)

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#25]
There is no point in connecting to Exchange with PowerShell at the start of Lab A, it is not used in either of these labs. If it is left in to show the student how to connect (Why? it was just used in the Mod 06 lab) we should include **Remove-PSSession** and show them how to use it correctly.

**Comment by JasonHershey** [comment]
I was just thinking the same thing when I looked at this (as part of adding the remove-pssession.  Will delete.
