### ISSUE TITLE
Remove-PSSession is missing

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#26]
At the end of **Module 6: Planning and managing Exchange Online recipients and permissions
Lab & LAK**, a step should be added to have the student run **Remove-PSSession** to release the resources and not tie up the Exchange server. Same problem at the start  of the **Module 07** Lab & LAK, and the end of the **Module 08** Lab & LAK, & **Module 10** Lab & LAK. (It _IS_ done correctly in the Module 11 Lab!)

**Comment by JasonHershey** [comment]
Updated the modules.
