### ISSUE TITLE
Why is it Holly Spencer in Adatum

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#27]
but Holly Dickson in Office 365?????

**Comment by JasonHershey** [comment]
Hmmm.  Looks like mix up in fictitious names.  I changed Dickson to Spencer in all files

**Comment by itbland** [comment]
That's what I was thinking, all names (except Francisco) changed in the new lab, and the scenario is that CL1 is Holly's desktop computer. I just jokingly added to my presentation that she just got married. The only concern I have is the idea that the Global Admin accounts should not be the regular account the the person uses (similar to on-prem domain advice). However, this security best practice is not mentioned in the class (I believe it is mentioned in the SecureScore information, but I could be wrong) and got edited out for time/simplicity.
________________________________

**Comment by itbland** [comment]
Here is the direction to use a dedicated global admin name instead of your real account (In which case using Holly Dickson for Holly Spencer's admin account makes sense.) [**Protect your Office 365 global administrator accounts**](https://support.office.com/en-us/article/Protect-your-Office-365-global-administrator-accounts-6B4DED77-AC8D-42ED-8606-C014FD947560) --but I think an explanation in the scenario and book would be a big help.
