### ISSUE TITLE
Mod 11 LAK, Ex 1, Task 4, Steps 23-31- IRM, need to use Outlook on CL3

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#28]
This will not work, The correct instructions would be to switch to CL3, open Outlook 2016, double-click the email (this will cause Outlook to load IRM), and try to forward the email.

**Comment by JasonHershey** [comment]
I just ran through this and it should work ok.  Note that instructions do not have you open Outlook 2016, but rather connect to OWA.  So, as long as they close out the browser, they should be fine signing back in with a different account.

**Comment by itbland** [comment]
Possibly the OWA had not updated the template to include IRM when I ran thru it , it was easier to tell students to use Outlook and be sure it would work. (I’ve seen delays of 15-45 minutes before OWA would have IRM available; Outlook will either work right away, or you can download the address book and force it.)

-Eric

**Comment by JasonHershey** [comment]
I added a note to the lab pointing this out and suggesting outlook on a different client as an alternative if IRM templates have not updated.
