### ISSUE TITLE
Mod 11 LAK, Ex 1,Task 2, Step 3 -  IRM sharing location

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#29]
The instructions in Mod 01 have us using the UK for Adatum, here we need to use "eu" in the
 **-RMSOnlineKeySharingLocation "https://sp-rms.eu.aadrm.com/TenantManagement/ServicePartner.svc"**
and the "na" should be listed in the note below that step.

**Comment by itbland** [comment]
I also would like to put in a step to show the students how to check the region that their data is in, either in the admin center (Organizational profile) or with PowerShell -- I guess it would make sense to use PowerShell (since we are using it here anyway) but I can't remember the new cmdlet that deals with tenant data location. (I suppose we could get Holly's mailbox properties and Select the name of the server.)

**Comment by JasonHershey** [comment]
Correcting and adding a note about checking tenant location. Easiest command to use, I think, is **Get-MsolCompanyInformation** which will return the CountryLetterCode

**Comment by itbland** [comment]
That will show what country you used during creation of the tenant. I know that SHOULD give you the correct continent, but I had one tenant for the US with the SharePoint server in AP! (I was showing the students the Organization profile and was astounded to see it—only happened once.)
Sorry, I’m drawing a blank, but I thought I had seen some new PowerShell commands (maybe in V2) that let you see this information.

--Eric

**Comment by JasonHershey** [comment]
There is a get | set MsolCompanyAllowedDataLocation.  I'm not expecting you could have SP data in a different area like that, without telling them to do it.

**Comment by itbland** [comment]
That’s the one I was thinking of (without knowing for sure that it would work!—And, It won’t: “If a company has not opted in the multinational feature or has no allowed data locations, then the cmdlet will return an empty list.”)

I WAS very surprised to see SharePoint in AP, I didn’t think they would do that--it was just a generic tenant for one of my classes. Must have been a fluke. The Easy button is your suggestion of: Get-MsolCompanyInformation, anything else will take more time just to check something that shouldn’t happen anyway.

Eric

**Comment by itbland** [comment]
Get-MsolCompanyInformation | Select Country

Would be the easiest, I would suppose…

-Eric

**Comment by itbland** [comment]
Get-MsolCompanyInformation | Select ReplicationScope

Is EXACTLY what we need!
Tested on GB, got EU
Tested on US, got NA

-Eric

**Comment by JasonHershey** [comment]
added that to a note.
