### ISSUE TITLE
Mod 11 LAK, Ex 2, Task 3, Step 2, missing link for Manage Retention Tags

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#30]
> 2. Under Delete, click Manage retention tags for mailboxes.

This link is no longer on this page in Office 365, Beth will need to browse to the Exchange admin center, (But was not added in Office 365 as a Customized admin - Exchange admin in Mod 02!)
Browsing directly to https://outlook.office365.com/ecp may work, but it would seem to me that this would be an opportunity to use the customized admin feature.
Unless the removal of the link on the O365 page was a mistake and it gets restored.

**Comment by JasonHershey** [comment]
Went ahead and just updated it so that Holly goes in to ECP to manage retention tags and policies.  Didn't want to start adding even more stuff to the lab.  Suspect this is going to get a major revamp in the next version to work with labels, assuming the functionality is equivalent by then.
