### ISSUE TITLE
Mod 11 Lab & LAK, Exercise 2, Task 4 Document Deleletion Policy is no more

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#31]
> Task 4: Configure content deletion and preservation policies

**Document deletion policies** needs to be updated to **Retention policy** (and significant changes to steps). Here are the step altered to work (but not necessarily the best version of this task):

1. On the Retention page, click **+Create**.
2. Type **Marketing Document Policy** in the Name box, and click **Next**.
3. Select **No, just delete content that’s older than**, type **7**, verify that the time is in **years**, and it is based on **when it was created**. Click **Next**.
4. Verify that **Let me choose specific locations** is selected. 
5. Turn “**off**” the switches for **Exchange email**, **OneDrive accounts**, and **Office 365 groups**.
6. Next to **SharePoint sites**, click **Choose sites**. On the Edit locations pane, click **Choose sites**.
7. In the Edit locations pane, type **https://AdatumLODxxxxx.sharepoint.com/sites/marketing/** in the search box, and then click the Search icon. Select the **Marketing** checkbox, and then click **Choose**.
8. Click **Done**, then click **Next**.
9. Read (but do not change) the Preservation Lock information, and Click **Next**.
10. Review the settings, and then click **Create this policy**.
11. **Close** the Marketing Document Policy  pane.

**Comment by JasonHershey** [comment]
redid this with current UI (basically like you described it)
