### ISSUE TITLE
Mod 11 Lab & LAK, Exercise 2, Task 4, Preservation policies are no more

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#32]
> Task 4: Configure content deletion and preservation policies

**Document preservation policies** needs to be updated to **Labels** (and significant changes to steps). Here are the step altered to work (but not necessarily the best version of this task):

1. In the **Security & Compliance center**, expand **Classifications**, and then click **Labels**
2. On the Labels page, click **+Create a label**.
3. Type **Retain contract details 7 years** in the Name box, and click **Next**.
4. On the Label settings pane, turn **Retention** “**On**”  
5. Verify that **Retain the content** is selected, that it is set for **7 years**, and that **No** is selected under **Do you want to delete it after that time**. Click **Next**.
6. Click **Create this label**.
7. On the Retain contract details 7 years pane, click **Auto-apply label**.
8. On the **Choose a label to auto-apply** pane, verify that **Retain contract details 7 years    7 years keep** is listed, and click **Next**.
9. Select **Apply label to content that contains specific words or phrases**, and click **Next**.
10. Type: **contract** in the **Keyword query editor** box, and click **Next**.
11. On the **Name your policy** pane, type: **Retain contract details**, and click **Next**. 
12. On the **Choose locations** pane, select: **Let me choose specific locations**.
13. Turn “**off**” the switch for **Office 365 groups**.
14. Next to **Exchange email**, click **Choose recipients**. On the **Edit locations pane**, click: **Choose recipients**. Select **Francisco Chaves**, click **Choose**, then click **Done**.
15. Next to **SharePoint sites**, click **Choose sites**. On the **Edit locations** pane, click **Choose sites**. 
16. In the **Edit locations** pane, type **https://AdatumLODxxxxx.sharepoint.com/sites/AcctsProj/** in the search box, and then click the **Search** icon. Select the **Accounts Project** checkbox, and then click **Choose**. Click **Done**, then click **Next**.
17. Verify the settings, then click **Auto-apply**.
18. Notice the Status is **On (Pending)** and click **Close**.

**Comment by JasonHershey** [comment]
redid this exercise to use new UI, but not using labels.  Since the text doesn't cover labels, stuck with retention policies and detecting words.

**Comment by itbland** [comment]
We use LabOnDemand labs, their web interface does not offer remote audio.
