### ISSUE TITLE
Mod 13 Lab and LAK Exercise 3, Task 1 - ADFS, Beth should sign in from CL3

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#33]
> 1, **On LON-CL1**, open Microsoft Edge, and then connect to https://portal.office.com.
> 2. Type **beth@adyyxxxxx.hostdomain.com** as the user name, and then press Tab.

If we setup ADFS correctly (we are not, we should add the URL to Local Intranet sites) then this **_will not work_**. With SSO properly setup, the domain user MUST be the person signed-in on a domain computer (**Holly** is signed-in on **LON-CL1**). This instruction should be changed to use **LON-CL3**. 
We should also add the adfs site to the Local Intranet zone, it will only take a minute and give a much better result.

**Comment by JasonHershey** [comment]
Nice catch. I updated the lab
