### ISSUE TITLE
Inconsistent custom domain names in Labs and LAK

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#35]
As I am typo hunting I can correct the names in the pull requests, but I need to know what are the correct "generic" names to use. I _THINK_ this is the most correct:

> **Adatumyyxxxxx.onmicrosoft.com** where the **_yyxxxxx_** is replaced by the student

and

> **Adatumyyxxxxx.hostdomain.com** (the custom domain) where the **_yyxxxxx_** is replaced by the student (and implied that each lab provider has their own hostdomain.com)

The **.onmicrosoft.com** references seem to be OK, but the custom domain is sometimes **yourdomain** (in Mod 02 this happens) and sometimes the instruction is to replace **_Adatumyyxxxxx_** and in others replace just the **_yyxxxxx_**. Which is correct?

(Also, aren't we all using the o365ready.com site? If so, it would be a lot easier to use Labxxxxx.o365ready.com for the custom domain in all lab documents--and a lot clearer, too)

**Comment by JasonHershey** [comment]
You are correct that replacing yyxxxxx is the correct way to reference, and your right about the implication that lab providers have their own hostdomain.  I don't _think_ that  everyone is using o365ready.com, but I am double-checking that assumption.  The design is based around the expectations that lab hosting providers have their own domain (and 'hostdomain' would vary by provider).

**Comment by JasonHershey** [comment]
Verified.  There are other lab hosting partners, so not everyone uses 0365Ready

**Comment by itbland** [comment]
OK, I **_FINALLY_** figured out how to get the _italics_ inside the **bold** domain names to work. 
`**Adatum**<!-- -->**_yyxxxxx_**<!-- -->**.onmicrosoft.com**`

Would these instructions be correct?:

 In all tasks:

- Where you see references to  **Adatum****_yyxxxxx_****.onmicrosoft.com**, replace  **_yyxxxxx_** with your unique Office 365 Number displayed in the online lab portal.

- Where you see references to  **Adatum****_yyxxxxx.hostdomain.com_**, replace the  **_yyxxxxx_** with your unique Office 365 Number, and **_hostdomain.com_** with your unique domain Name displayed in the online lab portal.
