### ISSUE TITLE
Skype Broadcast cannot be started

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#36]
I don't know if this is only a problem inside the LabOnDemand labs, but we cannot ever start the **Skype Broadcast** (we can share the pptx, but the buttons are all grayed out on the right.) 
My current theory is that none of the users have audio, so the server will not let us start the broadcast session. Holly and Beth can be in there, but Ada is left out in the cold waiting for Beth to press the **Start Broadcast** button.
Is it just me?

**Comment by LionelShaul** [comment]
I taught the course this week and hand the same problem with the broadcast.

Best regards,

Lionel Shaul

**Comment by JasonHershey** [comment]
I have reproed the problem, even in my local environment, by disabling Remote audio when connecting to the VMs.  I'm not familiar enough with real-world lab environment to know if there is an easy fix like 'be sure to enable remote audio'.  That would partially depend on if the computer you are remoting from has audio.  Another option might be to have students log into the meeting from their local computer, using the lab login.  checking with the powers-that-be regarding the lab environment question.

**Comment by JasonHershey** [comment]
@itbland what are your thoughts on having the student log into skype from their local computer?  That would assume they have S4B local, but if all else fails they can install it.  A bigger issue, I think, is they may have the wrong version.  It requires click-to-run Skype for example

**Comment by itbland** [comment]
Part of the old 20347A lab had us demonstrating the Skype Web client for the broadcast (It didn’t work as written because DC1 needed Desktop Experience!), if it (the web client) can be used by the Member who is presenting (not sure) then this could work. The real problem would be if the student did have S4B on their computer, the would have their own identity and would need to sign out and then sign in using the lab identity, and I do not like the idea of having a student reconfigure their own production computer for a class (negates the advantage/protection of using the VMs to keep the lab world separate from the REAL world.)

-Eric

**Comment by Apoc70** [comment]
Reconfiguring a production computer is never a good idea. But when it comes to dedicated computers used in a training class it's something different.
Another issue with the online labs is the fact that the labs are designed for en-US locales only. The RDP sessions always have issues when using the labs from operting systems using non en-US locales. A training provider I am worling with plans to rebuild the labs to fully support the local locale.

**Comment by JasonHershey** [comment]
quick update.  Having a conversation with LOD regarding this issue.

**Comment by JasonHershey** [comment]
Per LOD, there is a note in the Instructor Download Center for this course that this particular lab won't work in the lab environment.  They said it worked at one time, but something changed.  Still some investigation going on.  I'm going to add a note to the LAB, LAK to the same affect.
