### ISSUE TITLE
Mod 13 Lab & LAK, 2016 ADFS needs a restart

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#37]
Server 2016 requires a restart after **ADFS** **configuration** (at the end of Ex 1, Task 2)
![image](https://user-images.githubusercontent.com/20519564/27008226-aaee5c56-4e31-11e7-8457-49c7fe9ea22f.png)

(NOTE: This is after the configuration, not installation of the role. And, WAP does not need a restart.)

**Comment by JasonHershey** [comment]
added the restart.
