### ISSUE TITLE
where do we find the name of the external name server as provided by the Lab hosting provider.

### ISSUE THREAD

**Issue by johanvanwyk** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#39]

**Comment by itbland** [comment]
Each lab hosting company has their own solution—there have to be some “pre-Lab” instructions to get the domain name assigned and added to your lab machines and obtain a certificate. Which provider are you using? Someone here may be using the same provider and can give guidance.
(We use Learn on Demand Systems LabOnDemand.)

-Eric

**Comment by JasonHershey** [comment]
@johanvanwyk Did itbland's response get things sorted out for you?

**Comment by johanvanwyk** [comment]
Yes. Thank you.

Kind Regards,
Johan van Wyk | BI Team Lead
Mobile +27 (0) 81 396 5455 Email johan.vanwyk@isolve.co.za<mailto:johan.vanwyk@isolve.co.za> Web www.isolve.co.za<http://www.isolve.co.za/>
