### ISSUE TITLE
Pandoc version

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#4]
The MCT instructions state that we should use Pandoc 1.13.2 (a link to this version is included in the instructions). Should we be using the updated, current version (1.19.2.1)? https://github.com/jgm/pandoc/releases/tag/1.19.2.1

**Comment by StanReimer** [comment]
I will look into this. I know we have had some issues switching Pandoc versions.

**Comment by JasonHershey** [comment]
At this point, no one has officially tested with the updated version. We don't know of any reason it would not work, but at the same time, we know the older version works. If you do try the latest version, let us know if you run into problems.

**Comment by itbland** [comment]
I been using it on one of my computers and it seems to handle the formatting a little better (still not a flexible as markdown) but I haven't had any problems.
