### ISSUE TITLE
pandoc.ps1 fails to create allfiles zip

### ISSUE THREAD

**Issue by Apoc70** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#5]
As there is no AllFiles folder in the repository Copy AllFiles fails.

**Comment by GitHub-Soliman** [comment]
Moin Moin.
Agreed.
Maybe it is to be uilt manually for this new version (Why do the guys always delete stuff, they already had!).
_Tschüß,
__Michael.)

**Comment by JasonHershey** [comment]
Checked and there should be an \AllFiles.  Mod 4 has a file under \Labfiles.  I've added the folders\file to the repo.  Thanks for catching
