### ISSUE TITLE
Lab 4 

### ISSUE THREAD

**Issue by andrewbeldean** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#55]
Lab4 M4 : 7

Object reference was not set to an instance of an object Synchronization rules editor

Add transformation fails - the above error occurs, its the version of .net on the image that's the issue.

**Comment by JasonHershey** [comment]
Hi Andrew,  This appears to be a bug in AADConnect. You will notice there is a new note preceding the standard procedure with an alternate that should work fine.
