### ISSUE TITLE
Lab 9 External Sharing

### ISSUE THREAD

**Issue by daisuketanabe** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#56]
External User Sharing with "Edit link - no sign-in required" in Exercise 3 does not seem to work.

I had this issue with my production environment as well. It looks like changes to Sharing Settings vai Admin Center are not reflected to Sharepoint Site Collection. I waited for 2 days but the settings was not reflected. So it looks like there is a problem with Admin Center.

You can rectify this via Sharepoint Powershell.

1. Connect Sharepoint Online via Powershell
    Connect-SPOService -url https://adatumyyxxxxx-admin.sharepoint.com
2. Check Marketing Site Collection SharingCapability
    Get-SPOSite -identity https://adatumyyxxxxx.sharepoint.com/sites/marketing  | Select SharingCapability
3. You can see that SharingCapability is Disabled.
4. Enable External Sharing with Guest Link
    Set-SPOSite -identity https://adatumyyxxxxx.sharepoint.com/sites/marketing  -SharingCapability ExternalUserAndGuestSharing
5. Try Sharing Word Document, this should work now.

**Comment by JasonHershey** [comment]
Sorry, missed this issue come across. I'll double check and update the lab. Thanks for pointing out a fix.

**Comment by JasonHershey** [comment]
Still confirming. Had to set up a new tenant.

**Comment by JasonHershey** [comment]
@daisuketanabe I've run through this process a couple of times and can't reproduce the problem you had.  The procedure works at written, with the exception that the UI has changed a little bit.  But essentially its fine.  Its possible the problem was only temporary.  I have updated the procedure to match the current UI.
