### ISSUE TITLE
The LAB talk about v1.1.166 Azure Active Directory PowerShell V1, but DEPRECATED ? Should we update ?

### ISSUE THREAD

**Issue by Pascal-KOTTE** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#57]
LAB redirect to

> Task 1: Installing Microsoft Azure Active Directory module for Windows PowerShell
> On LON-CL1, open Microsoft Edge, and browse to http://aka.ms/t01i1o
> Download and install Microsoft Online Services Sign-In Assistant for IT Professionals RTW.
> In Microsoft Edge, connect to http://aka.ms/siqtee
> Download and install the Microsoft Azure AD module for Windows PowerShell.

But sounds DEPRECATED

[http://connect.microsoft.com/site1164](http://connect.microsoft.com/site1164)

> Azure Active Directory PowerShell V1 ("MSOL" module)
> We no longer support downloading Azure AD PowerShell V1 from Connect. Please go to https://www.powershellgallery.com/packages/MSOnline/ to download this module.
> Note that the MSOL module is being deprecated. For more information about this module, go to https://docs.microsoft.com/en-us/powershell/msonline/v1/azureactivedirectory
> For more information about the newer Azure Active Directory V2 PowerShell, please go to https://docs.microsoft.com/en-us/powershell/azuread/
> 

So what should we do ? 
Thanks to confirm in the LAB to keep older version, or replace with a better one ?

**Comment by itbland** [comment]
V2 is still in preview –quote: Version 2.0.0.17 (PowerShell V2 Public Preview) https://social.technet.microsoft.com/wiki/contents/articles/28552.microsoft-azure-active-directory-powershell-module-version-release-history.aspx

**Comment by itbland** [comment]
Oops, My bad—V2 is GA

I agree, Labs need to be redone for V2. (Boy, is that going to be a LOT of work)

Eric

From: Eric Bland<mailto:itbland50@live.com>
Sent: Monday, August 28, 2017 10:16 AM
To: MicrosoftLearning/20347-Enabling-and-Managing-Office365<mailto:reply@reply.github.com>; MicrosoftLearning/20347-Enabling-and-Managing-Office365<mailto:20347-Enabling-and-Managing-Office365@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Subject: RE: [MicrosoftLearning/20347-Enabling-and-Managing-Office365] The LAB talk about v1.1.166 Azure Active Directory PowerShell V1, but DEPRECATED ? Should we update ? (#57)

V2 is still in preview –quote: Version 2.0.0.17 (PowerShell V2 Public Preview) https://social.technet.microsoft.com/wiki/contents/articles/28552.microsoft-azure-active-directory-powershell-module-version-release-history.aspx

**Comment by JasonHershey** [comment]
thanks. will take a look at this in detail this week.

**Comment by itbland** [comment]
We also need to consider that the Exams and the book would need to be updated—classic argument of do we teach the technology or the exam?

Eric

**Comment by itbland** [comment]
> We will **_begin deprecating_** the older MSOnline module **_when all of the functionality_** of that module has been migrated to the newer AzureAD module.

https://docs.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-1.0 (emphasis added)

1. It appears that all of the TechNet docs for Office 365 still refer only to v1.
2. If you compare New-MSOLUser and New-AzureADUser, most MSOL functions are there, but not all. 
3. Also, there seems to be no equal to **LicenseOptions** _AND_ there seems to be no **Restore-AzureADUser** (just for starters).

Clearly there are new features in AzureAD PowerShell v2 that we should consider adding to the class, but it is not a replacement (yet).
Just my 2 cents.

**Comment by JasonHershey** [comment]
the V1 module still works fine for the lab. Not sure of what in the exams might reference specific version.  The course should get updated this fall (and I assume exams will also get updated about same time).  Leaving 'as is' seems to be the best option.
