### ISSUE TITLE
IT Group

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#65]
Hello.
On the xtremelabs environment, the "IT" group allready exist in teh ADDS. It's in the "IT" OU and is synced by the AADConnect setup.
I ran in a small confusion when the document instruct them to create a new distribution group named "IT" with a user within.
Did we miss something or is there a glitch in the documentation or in the xtremelabs setup ?

**Comment by normandk** [comment]
I just ran I to the same issue today in my class using Lan On Demand labs.

**Comment by itbland** [comment]
This happened in my (LOD) class last week--In Mod 04 Lab the IT Security group synced as a **_dist_** group--I assume an error in AD Connect that will be fixed???

**Comment by JasonHershey** [comment]
Checking on this

**Comment by itbland** [comment]
That IT Security group was always in the IT OU, but this month it has started to sync as a Universal Distribution Group into Azure AD—Is this a new “feature” of AD Connect, or a flaw?

________________________________

**Comment by itbland** [comment]
Any update? should we jet create an "IT2" dist group? (I'd rather know if the sync logic has changed)

**Comment by JasonHershey** [comment]
I don't have an answer on the sync logic yet.  But, for now, I think your solution @itbland is a good one, create an IT2 dist group instead.  We are in the process of updating this course now so will likely change this to something else that makes more sense in the context of the lab, but short term, this fix works.
