### ISSUE TITLE
TXT Record not Verifying

### ISSUE THREAD

**Issue by BKinyua** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#66]
I have been trying to create a domain as instructed on the Labs without success.
Lab Network info is;
**Address**
64.64.206.18
**O365 Blob**
AdatumAVRZQ6
**UPN name**
AVRZQ6a

I have gone ahead and created a Primary Forward Look-up Zone called **AdatumAVRZQ6.hostdomain.com**
Then added the TXT record with name as blank and the MS=ms12345678 (as generated at the domain creation steps).
Also added the A record and edited the SOA and NS records accordingly. In fact the NS record resolved successfully.

Am I missing anything?

**Comment by itbland** [comment]
Who is your lab provider? They need to give you a domain name that you can use in place of “hostdomain.com” (and they need to create a delegation to your lab IP) Look in the lab provider’s instructions.

-Eric

________________________________

**Comment by renaudwangler** [comment]
Hi !
For the MLO environment, you MUST use the provided lab guide, downloading it from the "Documents" menu of your lab environment. In this document, they tell you to use AVRZQ6a.xtremelabs.us as docmain.
Hope this helps ;)

**Comment by BKinyua** [comment]
Thanks everyone for the help. I was not providing xtremelabs.us as the hostdomain. Thank you All.
