### ISSUE TITLE
First two lines in Lab 1 are not rendered correctly by pandoc

### ISSUE THREAD

**Issue by mdwoernhard** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#67]
I work with a fresh clone. pandoc.ps1 does not render the first two lines in Lab 1 (20347A_LAB_01.md) as Heading 1 styles in the resulting Word document. Opening the file in notepad, copying all content and pasting i a new text document and saving it as 20347A_LAB_01.md resolves the problem.

**Comment by JasonHershey** [comment]
It appears to be an issue with an encoding marker in the text file. spotted it in VS Code.  Will get a new version uploaded.
