### ISSUE TITLE
PanDoc.ps1 - bug with pandoc.msi 2.1.1

### ISSUE THREAD

**Issue by pcasti** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#68]
the bug in current line 32 
    pandoc $inputFile -o $outputFile --reference-**docx**=template.docx 

you must replace line 32, with:
    pandoc $inputFile -o $outputFile --reference-**doc**=template.docx

**Comment by mdwoernhard** [comment]
Please note that the instructions specifically state to use pandoc version 1.13.2. Besides your correction mentioned above, new pandoc versions (both 1.19.x and 2.x) does not render the resulting document identidally: there is a visual glitch with the result-box (after last steps) - the block quote template is not applied.

**Comment by JasonHershey** [comment]
updated line 32.  There are also conversations about testing newer versions of pandoc
