### ISSUE TITLE
Microsoft Connect Has Been Retired (Mod 2 Lab)

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#69]
In Microsoft Edge, browse to [http://aka.ms/siqtee](http://aka.ms/siqtee), and then click Save.

The link to download AdministrationConfig-en.msi is broken, Unless someone knows of another download site, it can be installed using "Install-Module MSOnline" in PowerShell directly (I would assume this is the preferred method: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)). However, this means no shortcut on the desktop and many more tasks in later labs will need to be re-written!
(Add--This happens again on LON-DS1 in Mod 4 Lab.)

From the link above:

- Open an administrator-level PowerShell command prompt.
- Run the **Install-Module MSOnline** command.
- If prompted to install the NuGet provider, type **Y** and press ENTER.
- If prompted to install the module from PSGallery, type **Y** and press ENTER.

**Comment by JasonHershey** [comment]
Yes.  Ran into this as part of reviewing/updating a rev to the course. The URLs literally started going wonky this past week.  The update is to do exactly what you just proposed. (so thanks for verifying that the change makes sense.)
