### ISSUE TITLE
Domain Purpose is back

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#71]
AND, when creating users, you must now explicitly choose to give them a license.

(Working on a pull for Mod 01, 02 and 03)

**Comment by JasonHershey** [comment]
Thanks. I'll verify the course update gets this update. I think we spotted that in testing. I'll be going through and applying any UI-only course changes back to this version shortly.

**Comment by JasonHershey** [comment]
fyi, labs have been updated for the just RTMed version of the course

**Comment by itbland** [comment]
This is not fixed in the new labs, please reopen.
We need to specify the "Domain Purpose" either in Mod 01 Lab or Mod 03 Lab.

**Comment by JasonHershey** [comment]
I'm spinning up a new test tenant.  I don't remember being asked to do this during the course.

**Comment by itbland** [comment]
Domain purpose is back (I've done 2 installs since I raised this issue, screenshot below). 
Two weeks ago the users created in the admin center had a license, but last week I again had to select a license (that I first saw in March), so I'm not sure what is happening with that.
![o365capturedomain](https://user-images.githubusercontent.com/20519564/40339049-1c3295dc-5d3e-11e8-8344-4da702e37da2.PNG)
![o365capturelicense](https://user-images.githubusercontent.com/20519564/40339050-1c46bbe8-5d3e-11e8-9099-2109d5c48931.PNG)

**Comment by JasonHershey** [comment]
Updated Mod 1 tenant creation to reflect current UI.
For user adition, I'm seeing licenses applied at this point. That might have been a temporary issues
![20347-user-add](https://user-images.githubusercontent.com/14264978/41212455-e4332fc4-6cf2-11e8-9290-9a1f7fee1b5f.PNG)
