### ISSUE TITLE
Module 11 Azure Information Protection

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#72]
Instructions should be updated to use the AADRM module. Set-IRMConfugaration doesn't work anymore.

**Comment by itbland** [comment]
Not needed, just skip the PowerShell.

**Comment by itbland** [comment]
FYI: https://github.com/MicrosoftLearning/10997-O365AdministrationandTroubleshooting/issues

**Comment by JasonHershey** [comment]
yes, we just went through this discussion as part of updates for the next version.  For at least some tenants, its still working the old way.  The plan is to do a check to see if tenant has been updated, and if not, then instruct to use the powershell commands (but default will be to skip)
