### ISSUE TITLE
Mod 03 Lab, Ex 4

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#77]
Mobile Device Management no longer appears under DLP in the Security Center until it is activated. This might be a temporary problem, or it may be a change for Trial accounts--the only way I could activate MDM was to search for it on the Home page of the O365 Admin Center.

Also, since it takes several hours to be set up, how do we expect students to do the lab in the time allotted?
(EDIT: After I figured out how to enable--it took about 10 minutes to become available, maybe not so much of a problem.)

**Comment by guapsc** [comment]
In the HOME menu of portal, in search you tap "mobile"

**Comment by JasonHershey** [comment]
I'm ramping up a test tenant this weekend. I'll run through the procedure and see what new updates need made.

**Comment by JasonHershey** [comment]
Updated to add link directly to MDM activation page.
