### ISSUE TITLE
Office not install on LON-CL3?

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#78]
In the new Mod 05 lab, we no longer install Office Pro Plus on LON-CL3, yet we need Office on LON-CL3  for the Mod 08 lab. I haven't seen the new VMs--Is Office pre-installed now on LON-CL3, or is this going to be a problem?

**Comment by JasonHershey** [comment]
Sorry, I thought I had responded.  In Mod 5, exercise 2, task 2, Office gets installed on LON-CL3
