### ISSUE TITLE
Changes to SourceAnchor - Mod 13 Lab

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#8]
> **Azure AD Connect: Design concepts - Using msDS-ConsistencyGuid as sourceAnchor**  https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-design-concepts#using-msds-consistencyguid-as-sourceanchor

Will this require an update to the Mod 13 lab? 
The documentation states if AD FS is setup manually, the **msDS-ConsistencyGuid** must be added to the claims.

**Comment by JasonHershey** [comment]
will research

**Comment by itbland** [comment]
Update - The lab works as written. Since the Adatum.com domain has never used the msDS-ConsistencyGuid, (per the documentation) AD Connect populates it with the GUID, so everything works. While I would love to go back to showing adding claim rules, I think (previously) removing that from the lab was a wise time-saving edit. Hopefully, this information will be added to the book.

**Comment by JasonHershey** [comment]
Thanks for the update.  All these comments/issues should be reviewed when the next rev of the course comes around.  FYI, in the ideal, I would not close these issues, but let you and others who are commenting to close... but with so many open, its a bit easier to sort them out if I close as things get taken care of. Feel free to reopen if needed.

**Comment by itbland** [comment]
@JasonHershey, I have no problem at all with you closing the issues, and I can see the close button on the open issues, but I don't see a way to "re-open" one?? (Or, do you mean, just start a new issue and reference the old, closed one?) Thanks for all the work on these labs, btw.

**Comment by JasonHershey** [comment]
Well shoot.  Apparently you can't reopen the issue if I close it, since I've got collaborater perms.... you could if someone else closed them.  So, for now just comment and let me know you don't think it should be closed (or open a new one).
