### ISSUE TITLE
Pandoc version

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#81]
Why does this class use pandoc 1.13.2 when the other classes are using 1.19.2?

**Comment by JasonHershey** [comment]
Updated to work with 1.19.2. sorry for the delay.  I actually couldn't find other courses using 1.19.2 (any I was familiar with.  But, while working on publishing some recent courses I tested with 1.19.2 and reviewed instructions for any other needed changes.  those are included too.

**Comment by itbland** [comment]
Much appreciated!
10997 O365 Admin & Troubleshooting, and all of the (now previous) Azure courses I also teach specified 1.19.2, as well as the Windows 10 classes. It was a minor pain to uninstall/reinstall or just take the chance that it would generate an error. Thanks!
