### ISSUE TITLE
Error documentation Lab5

### ISSUE THREAD

**Issue by travellingtrainer** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#89]
In lab5, task1, step23. There are now 3 xml files:
Configuration-Office365-x64.xml
Configuration-Office365-x86.xml
Configuration-Office2019Enterprise.xml
In lab5, task2, step1. Modify configuration.xml, which no longer exists.

In lab5, task1 ,step20. 2016 desktop and mobile apps is no longer presented, but can be set.

Please update Instructions documentation.

**Comment by JasonHershey** [comment]
thanks. We'll go through this lab and make fixes

**Comment by travellingtrainer** [comment]
Hi Jason, I think you will need to go through the whole set of labs, because I am getting lots of errors and differences to the documentation in every lab. SharePoint, Yammer, RMS all have issues: E.g. RMS : Set-IRMConfiguration -RMSOnlineKeySharingLocation "https://sprms.eu.aadrm.com/TenantManagement/ServicePartner.svc" Gives an error that this should not be used and setup should be performed in Azure RMS.

**Comment by WigF1** [comment]
For the sake of a few weeks, is it worth it? The course expires soon. Besides, RMS is enabled by default in all new tenants and as the error says, you need to manage it differently.

Also, the labs are in GitHub. You can submit your own changes. We don't have to rely on Jason alone, that was the whole point of putting them in GitHub.

Thanks for all the work, Jason.



Get Outlook for Android<https://aka.ms/ghei36>

**Comment by JasonHershey** [comment]
Updated Mod 5 Lab and Answer key to address issues referenced in the original issue.  thanks for letting us know.
