### ISSUE TITLE
Have you abandoned this class before Microsoft retire it?

### ISSUE THREAD

**Issue by travellingtrainer** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#90]
Module 8 teaches Skype for business. No mention of Teams. 
But the lab hasn't been updated to include teams either. Go to Skype for business"
When it is now "Teams and Skype" None of the pages presented correspond with lab guide.

**Comment by JasonHershey** [comment]
Thanks for the pointer.  We'll go through the lab and update to match current UI.

**Comment by JasonHershey** [comment]
Updated Module 8 to fix references for Skype for Business admin center.  Tasks in the lab are still performed in the (legacy) Skype for Business admin center -- not the Teams admin center.  So fixed navigation for how to get there. that is all that needed updated.
